# This file was generated by GoReleaser. DO NOT EDIT.
class Psutils < Formula
  desc "Helper for common task."
  homepage "https://github.com/psmarcin/psutils/"
  version "0.5.6"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/psmarcin/psutils/releases/download/v0.5.6/psutils_0.5.6_Darwin_x86_64.tar.gz"
    sha256 "949c3b4dcc718ceb4fcdc921f2e57cc19281ed51fc1bb04491ad15115a7eaca8"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/psmarcin/psutils/releases/download/v0.5.6/psutils_0.5.6_Linux_x86_64.tar.gz"
      sha256 "5e4a1adfd2b8faa509af5025cfe08212e0169b401e886ad3a1f811d7b5505499"
    end
  end

  def install
    bin.install "psutils"
  end

  def caveats; <<~EOS
    psutils --help for usage information
  EOS
  end

  test do
    system "#{bin}/psutils --version"
  end
end
