# This file was generated by GoReleaser. DO NOT EDIT.
class Psutils < Formula
  desc "Helper for common task."
  homepage "https://github.com/psmarcin/psutils/"
  version "0.7.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/psmarcin/psutils/releases/download/v0.7.1/psutils_0.7.1_Darwin_x86_64.tar.gz"
    sha256 "bc569e1408cdd0ff07d7a339abb30c74f3ca18228d976999cf27551c23b7edea"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/psmarcin/psutils/releases/download/v0.7.1/psutils_0.7.1_Linux_x86_64.tar.gz"
      sha256 "cb64428217e572530239fac297938752400855583cb16c9a3c3a9432e630e832"
    end
  end

  def install
    bin.install "psutils"
  end

  def caveats; <<~EOS
    psutils --help for usage information
  EOS
  end

  test do
    system "#{bin}/psutils --version"
  end
end
