# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "custom_download_strategy"
class Psutils < Formula
  desc "Helper for common task."
  homepage "https://github.com/psmarcin/psutils/"
  version "0.5.2"
  bottle :unneeded

  if OS.mac?
    url "http://github.com/psmarcin/psutils/releases/v0.5.2/psutils_0.5.2_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "b4a1253ed095a0b44007780e84664950768ca4cd01d6ade768bcb517adf3b1c5"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "http://github.com/psmarcin/psutils/releases/v0.5.2/psutils_0.5.2_Linux_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "a060738f2481db23dd458618baa44b1371a5366c0a1a9c8ae5ba1676e5852466"
    end
  end
  
  depends_on "bash"

  def install
    bin.install "program"
  end

  def caveats; <<~EOS
    psutils --help for usage information
  EOS
  end

  plist_options :startup => false

  def plist; <<~EOS
    <?xml version="1.0" encoding="UTF-8"?>

  EOS
  end

  test do
    system "#{bin}/program --version"
  end
end
